### ISSUE TITLE
AttributeError: 'QWidget' object has no attribute 'set_canvas'

### ISSUE THREAD

**Issue by tuxgvf** [Partmedia/s2p-view#1]
Hi

I am very interested by your tool, but I can run your script.

What do I need to do with the make command? Should I run it on cmd? anaconda prompt? or where? Could you please clarify?

I had to use this command  to avoid error on the layout and about 
python -m PyQt5.uic.pyuic -x layout.ui -o layout.py

I have this error remaining
AttributeError: 'QWidget' object has no attribute 'set_canvas'

this seems to be coming from layout.py

Can you help me? Sharing your layout.py can probably help me to solve the issue.

Thanks

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.canvas = FigureCanvas(self.centralwidget)
        self.canvas.setObjectName("canvas")
        self.verticalLayout_2.addWidget(self.canvas)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineRange = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineRange.sizePolicy().hasHeightForWidth())
        self.lineRange.setSizePolicy(sizePolicy)
        self.lineRange.setClearButtonEnabled(True)
        self.lineRange.setObjectName("lineRange")
        self.horizontalLayout_3.addWidget(self.lineRange)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(0, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboDisplay = QtWidgets.QComboBox(self.centralwidget)
        self.comboDisplay.setObjectName("comboDisplay")
        self.comboDisplay.addItem("")
        self.comboDisplay.addItem("")
        self.comboDisplay.addItem("")
        self.comboDisplay.addItem("")
        self.comboDisplay.addItem("")
        self.comboDisplay.addItem("")
        self.comboDisplay.addItem("")
        self.verticalLayout.addWidget(self.comboDisplay)
        self.comboUnit = QtWidgets.QComboBox(self.centralwidget)
        self.comboUnit.setObjectName("comboUnit")
        self.comboUnit.addItem("")
        self.comboUnit.addItem("")
        self.comboUnit.addItem("")
        self.verticalLayout.addWidget(self.comboUnit)
        self.smithBox = QtWidgets.QGroupBox(self.centralwidget)
        self.smithBox.setEnabled(True)
        self.smithBox.setObjectName("smithBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.smithBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkLabels = QtWidgets.QCheckBox(self.smithBox)
        self.checkLabels.setObjectName("checkLabels")
        self.verticalLayout_3.addWidget(self.checkLabels)
        self.checkVSWR = QtWidgets.QCheckBox(self.smithBox)
        self.checkVSWR.setObjectName("checkVSWR")
        self.verticalLayout_3.addWidget(self.checkVSWR)
        self.verticalLayout.addWidget(self.smithBox)
        self.checkS11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkS11.setObjectName("checkS11")
        self.verticalLayout.addWidget(self.checkS11)
        self.checkS21 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkS21.setObjectName("checkS21")
        self.verticalLayout.addWidget(self.checkS21)
        self.checkS12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkS12.setObjectName("checkS12")
        self.verticalLayout.addWidget(self.checkS12)
        self.checkS22 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkS22.setObjectName("checkS22")
        self.verticalLayout.addWidget(self.checkS22)
        self.checkLegend = QtWidgets.QCheckBox(self.centralwidget)
        self.checkLegend.setChecked(True)
        self.checkLegend.setObjectName("checkLegend")
        self.verticalLayout.addWidget(self.checkLegend)
        self.plotButton = QtWidgets.QPushButton(self.centralwidget)
        self.plotButton.setObjectName("plotButton")
        self.verticalLayout.addWidget(self.plotButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.action_Open.setIcon(icon)
        self.action_Open.setObjectName("action_Open")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("help-about")
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.actionReload = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("view-refresh")
        self.actionReload.setIcon(icon)
        self.actionReload.setObjectName("actionReload")
        self.actionClose_All = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-close")
        self.actionClose_All.setIcon(icon)
        self.actionClose_All.setObjectName("actionClose_All")
        self.actionSave_Plot = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionSave_Plot.setIcon(icon)
        self.actionSave_Plot.setObjectName("actionSave_Plot")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.actionReload)
        self.menu_File.addAction(self.actionSave_Plot)
        self.menu_File.addAction(self.actionClose_All)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.comboDisplay.setCurrentIndex(0)
        self.comboUnit.setCurrentIndex(1)
        self.comboDisplay.currentTextChanged['QString'].connect(self.plotButton.click)
        self.comboUnit.currentIndexChanged['QString'].connect(self.plotButton.click)
        self.lineRange.returnPressed.connect(self.plotButton.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "S-Parameter Viewer"))
        self.lineRange.setPlaceholderText(_translate("MainWindow", "Range (e.g. \"1-4 ghz\")"))
        self.comboDisplay.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.comboDisplay.setItemText(1, _translate("MainWindow", "Phase"))
        self.comboDisplay.setItemText(2, _translate("MainWindow", "Smith"))
        self.comboDisplay.setItemText(3, _translate("MainWindow", "Z Real"))
        self.comboDisplay.setItemText(4, _translate("MainWindow", "Z Imag"))
        self.comboDisplay.setItemText(5, _translate("MainWindow", "Y Real"))
        self.comboDisplay.setItemText(6, _translate("MainWindow", "Y Imag"))
        self.comboUnit.setItemText(0, _translate("MainWindow", "Hz"))
        self.comboUnit.setItemText(1, _translate("MainWindow", "MHz"))
        self.comboUnit.setItemText(2, _translate("MainWindow", "GHz"))
        self.smithBox.setTitle(_translate("MainWindow", "Smith"))
        self.checkLabels.setText(_translate("MainWindow", "Labels"))
        self.checkVSWR.setText(_translate("MainWindow", "VSWR"))
        self.checkS11.setText(_translate("MainWindow", "S11"))
        self.checkS21.setText(_translate("MainWindow", "S21"))
        self.checkS12.setText(_translate("MainWindow", "S12"))
        self.checkS22.setText(_translate("MainWindow", "S22"))
        self.checkLegend.setText(_translate("MainWindow", "Legend"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menuHelp.setTitle(_translate("MainWindow", "He&lp"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionReload.setText(_translate("MainWindow", "Reload"))
        self.actionReload.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionClose_All.setText(_translate("MainWindow", "Close All"))
        self.actionClose_All.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionSave_Plot.setText(_translate("MainWindow", "Save Plot"))
        self.actionSave_Plot.setShortcut(_translate("MainWindow", "Ctrl+S"))

from matplotlib.backends.backend_qt5agg import FigureCanvas

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

**Comment by Partmedia** [comment]
Hi there,

You can run the `make` command on a Unix shell prompt in the top-level directory where the *Makefile* is located. If you are on Windows, you need to install a make command (for example, *mingw32-make*) and then run it from any shell (*cmd.exe* is fine).

The workaround you suggested is also fine. I will look at converting this into a Python script, so that there is no dependency on `make`.

You might be running into this error because you are using an old version of pyqt5 (5.9.2 from your pyuic5 output). Is there a chance you can upgrade to a later version (I'm using 5.15)? I'll also look at making this dependency line more clear.

**Comment by Partmedia** [comment]
Reviewing the Makefile, it could also be that a few text substitutions are missing. It would be best if you could install `make` and run the Makefile, replacing the *pyuic5* commands if necessary for your system.

**Comment by tuxgvf** [comment]
Hi thanks a lot for your reply.
That's correct I am running pyuic5 5.9.2, I will try to make an upgrade in last chance, or try to run make into another computer. 

The issue is the following:
self.canvas = FigureCanvas(self.centralwidget)
returns me the following error AttributeError: 'QWidget' object has no attribute 'set_canvas'

so I replaced it by :

        import matplotlib.pyplot as plt
        self.figure = plt.figure()
        self.canvas = FigureCanvas(self.figure)

Do you know what argument should I do? It seems only this line causes a problem.

Could you share your ui to py code for the layout code?

Thanks a lot
V

**Comment by tuxgvf** [comment]
I just tried with the pyuic (5.15)got the same behavior, likely the same file is generated... and same error 

V

**Comment by Partmedia** [comment]
It's not just pyuic that might be old, but also the underlying Python libraries, in particular, py-qt5 and py-qt5-sip. I don't know what these packages are called on your operating system. What operating system are you using?

Try this release binary that I've just made: https://github.com/Partmedia/s2p-view/releases/download/v0.1.2/s2p-view

If this still doesn't work, something is incompatible between our library versions.

**Comment by tuxgvf** [comment]
Hi
Thanks for your time
I'm using a win10 PC. Sorry I'm not a Python expert, that can I do with your binary file? Is it a python encrypted file?
V

**Comment by Partmedia** [comment]
You may be able to run it by double-clicking it, or typing `python s2p-view` at the command-line.

**Comment by tuxgvf** [comment]
it works just great!! Thanks!

I would be happy to fix my issue. Can you share the layout.py? is it possible?

Thanks

**Comment by Partmedia** [comment]
Glad to hear it works now. The *layout.py* is generated from *layout.ui*, but there are extra steps that the *Makefile* will run for you. If you want to build the binary yourself, you should install *make*.

**Comment by tuxgvf** [comment]
I'm just curious your "binary file" as no extension but it works... do you know why? :) I'm just curious.
Thanks
V

**Comment by Partmedia** [comment]
See this: https://docs.python.org/3/library/zipapp.html
